package Game;

import Game.GameConstants.Terrain;
import Game.GameConstants.ThingType;

/*
 * This Class represents a random special income "Thing" in the Game,
 * providing specialized special income functionality
 * Implements the Incomable interface to allow generation of income
 * Terrain is an enum defined in GlobalConstants class
 */
public class SpecialIncome extends Thing implements IIncomable {
	private int income;			//amount of income generated by this SpecialIncome
	private Terrain terrain;	//terrain required to play this SpecialIncome
	
	public SpecialIncome( Terrain terrain, String name, String frontFileName, int income)
	{
		super(ThingType.SPECIAL_INCOME, name, frontFileName);
		
		this.income = income;
		this.terrain = terrain;
		
		isFlipped = false;
	}
	
	public int getIncome()
	{
		return income;
	}
	
	public Terrain getTerrain()
	{
		return terrain;
	}
}
